name = "ssak-writing"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "ssak-db"
database_id = "bbfdd051-6445-42fa-be52-73d2b503f103"
