name = "ssak-writing"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "ssak-db"
database_id = "b2907d21-5617-4e2b-8cd0-003387eb935a"
